// Mocks generated by Mockito 5.1.0 from annotations
// in ditonton/test/presentation/pages/tv_detail_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i13;
import 'dart:ui' as _i14;

import 'package:ditonton/common/state_enum.dart' as _i10;
import 'package:ditonton/domain/entities/episode.dart' as _i12;
import 'package:ditonton/domain/entities/tv.dart' as _i11;
import 'package:ditonton/domain/entities/tv_detail.dart' as _i8;
import 'package:ditonton/domain/usecases/get_episode_tv.dart' as _i4;
import 'package:ditonton/domain/usecases/get_tv_detail.dart' as _i2;
import 'package:ditonton/domain/usecases/get_tv_recommendation.dart' as _i3;
import 'package:ditonton/domain/usecases/get_watchlist_status.dart' as _i5;
import 'package:ditonton/domain/usecases/remove_watchlist.dart' as _i7;
import 'package:ditonton/domain/usecases/save_watchlist.dart' as _i6;
import 'package:ditonton/presentation/provider/tv_detail_notifier.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeGetTvDetail_0 extends _i1.Fake implements _i2.GetTvDetail {}

class _FakeGetTvRecommendations_1 extends _i1.Fake
    implements _i3.GetTvRecommendations {}

class _FakeGetEpisodeTv_2 extends _i1.Fake implements _i4.GetEpisodeTv {}

class _FakeGetWatchListStatus_3 extends _i1.Fake
    implements _i5.GetWatchListStatus {}

class _FakeSaveWatchlist_4 extends _i1.Fake implements _i6.SaveWatchlist {}

class _FakeRemoveWatchlist_5 extends _i1.Fake implements _i7.RemoveWatchlist {}

class _FakeTvDetail_6 extends _i1.Fake implements _i8.TvDetail {}

/// A class which mocks [TvDetailNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvDetailNotifier extends _i1.Mock implements _i9.TvDetailNotifier {
  MockTvDetailNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetTvDetail get getTvDetail =>
      (super.noSuchMethod(Invocation.getter(#getTvDetail),
          returnValue: _FakeGetTvDetail_0()) as _i2.GetTvDetail);
  @override
  _i3.GetTvRecommendations get getTvRecommendations => (super.noSuchMethod(
      Invocation.getter(#getTvRecommendations),
      returnValue: _FakeGetTvRecommendations_1()) as _i3.GetTvRecommendations);
  @override
  _i4.GetEpisodeTv get getEpisodeTv =>
      (super.noSuchMethod(Invocation.getter(#getEpisodeTv),
          returnValue: _FakeGetEpisodeTv_2()) as _i4.GetEpisodeTv);
  @override
  _i5.GetWatchListStatus get getWatchListStatus =>
      (super.noSuchMethod(Invocation.getter(#getWatchListStatus),
          returnValue: _FakeGetWatchListStatus_3()) as _i5.GetWatchListStatus);
  @override
  _i6.SaveWatchlist get saveWatchlist =>
      (super.noSuchMethod(Invocation.getter(#saveWatchlist),
          returnValue: _FakeSaveWatchlist_4()) as _i6.SaveWatchlist);
  @override
  _i7.RemoveWatchlist get removeWatchlist =>
      (super.noSuchMethod(Invocation.getter(#removeWatchlist),
          returnValue: _FakeRemoveWatchlist_5()) as _i7.RemoveWatchlist);
  @override
  _i10.RequestState get tvState =>
      (super.noSuchMethod(Invocation.getter(#tvState),
          returnValue: _i10.RequestState.Empty) as _i10.RequestState);
  @override
  _i8.TvDetail get tvDetail => (super.noSuchMethod(Invocation.getter(#tvDetail),
      returnValue: _FakeTvDetail_6()) as _i8.TvDetail);
  @override
  List<_i11.Tv> get tvRecommendations =>
      (super.noSuchMethod(Invocation.getter(#tvRecommendations),
          returnValue: <_i11.Tv>[]) as List<_i11.Tv>);
  @override
  _i10.RequestState get seasonState =>
      (super.noSuchMethod(Invocation.getter(#seasonState),
          returnValue: _i10.RequestState.Empty) as _i10.RequestState);
  @override
  Map<int, List<_i12.Episode>> get seasons =>
      (super.noSuchMethod(Invocation.getter(#seasons),
              returnValue: <int, List<_i12.Episode>>{})
          as Map<int, List<_i12.Episode>>);
  @override
  _i10.RequestState get recommendationState =>
      (super.noSuchMethod(Invocation.getter(#recommendationState),
          returnValue: _i10.RequestState.Empty) as _i10.RequestState);
  @override
  String get message =>
      (super.noSuchMethod(Invocation.getter(#message), returnValue: '')
          as String);
  @override
  bool get isAddedToWatchlist =>
      (super.noSuchMethod(Invocation.getter(#isAddedToWatchlist),
          returnValue: false) as bool);
  @override
  String get watchlistMessage =>
      (super.noSuchMethod(Invocation.getter(#watchlistMessage), returnValue: '')
          as String);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  _i13.Future<void> fetchTvSeriesDetail(int? id) => (super.noSuchMethod(
      Invocation.method(#fetchTvSeriesDetail, [id]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i13.Future<void>);
  @override
  _i13.Future<void> fetchTvEpisodeBySeason(
          int? idTv, int? idSeason, int? seasonNumber) =>
      (super.noSuchMethod(
              Invocation.method(
                  #fetchTvEpisodeBySeason, [idTv, idSeason, seasonNumber]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i13.Future<void>);
  @override
  _i13.Future<void> addWatchlist(_i8.TvDetail? tvDetail) => (super.noSuchMethod(
      Invocation.method(#addWatchlist, [tvDetail]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i13.Future<void>);
  @override
  _i13.Future<void> removeFromWatchlist(_i8.TvDetail? tvDetail) =>
      (super.noSuchMethod(Invocation.method(#removeFromWatchlist, [tvDetail]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i13.Future<void>);
  @override
  _i13.Future<void> loadWatchlistStatus(int? id) => (super.noSuchMethod(
      Invocation.method(#loadWatchlistStatus, [id]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i13.Future<void>);
  @override
  void addListener(_i14.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i14.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}
